// ============================================================================
//  Skill "Feature Requests" — PROMPT + user-facing STRINGS.
//  Prompt text/rules and localized reply strings only — no logic (that's skill.js).
//  The output JSON must keep matching what skill.js expects.
//
//  Two kinds of user-facing text here:
//    1. Fixed SCAFFOLDING strings (errors, cancel, caption) -> reply(lang) {en,pt}.
//    2. The turn REPLY (ack + next question) is GENERATED by the model in ctx.lang
//       (see buildClarifySystem), so it is not a fixed string.
//  The generated DOCUMENT (buildDocSystem) is ALWAYS English by design — the artifact
//  is destined for the owner's (English) codebase — even when the chat is in another
//  language. Internal/classification prompts stay English.
// ============================================================================

// ---- JSON Schema for the per-turn clarify call (output_config.format) --------
// One structured call per owner message: fold the latest answer into a running
// draft, decide whether to keep clarifying / finalize / cancel, and (when
// clarifying) write the next WhatsApp reply in the conversation language.
export const CLARIFY_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["status", "draft", "reply"],
  properties: {
    // clarifying = ask more; finalize = owner signalled done -> render the doc;
    // cancel = owner abandoned the idea.
    status: { type: "string", enum: ["clarifying", "finalize", "cancel"] },
    // The running spec, re-emitted (carried forward + updated) EVERY turn. All
    // fields nullable / arrays so an early turn can leave gaps.
    draft: {
      type: "object",
      additionalProperties: false,
      required: [
        "title",
        "one_liner",
        "problem",
        "trigger",
        "actors",
        "steps",
        "data_touched",
        "edge_cases",
        "open_questions",
      ],
      properties: {
        title: { type: ["string", "null"] }, // short feature name -> filename slug
        one_liner: { type: ["string", "null"] }, // one-sentence summary
        problem: { type: ["string", "null"] }, // the pain / motivation
        trigger: { type: ["string", "null"] }, // how the user starts the flow
        actors: { type: "array", items: { type: "string" } },
        steps: { type: "array", items: { type: "string" } }, // user-POV flow
        data_touched: { type: ["string", "null"] }, // data / services involved
        edge_cases: { type: "array", items: { type: "string" } },
        open_questions: { type: "array", items: { type: "string" } }, // unresolved
      },
    },
    // The WhatsApp message to send this turn when status="clarifying" (ack + the next
    // question(s)), written in the conversation language. Ignored on finalize/cancel.
    reply: { type: ["string", "null"] },
  },
};

// ISO 639-1 -> a name the model reliably writes in. Extend as maintained langs grow.
const LANG_NAME = { en: "English", pt: "Brazilian Portuguese" };
function langName(lang) {
  return LANG_NAME[lang] || `the language with ISO 639-1 code "${lang}"`;
}

// ---- Clarify call (the conversation engine) ----------------------------------
export function buildClarifySystem(owner, lang) {
  return `You are ${owner}'s product assistant on WhatsApp. ${owner} is capturing a NEW
FEATURE idea for software he is building (a note to himself). Your job is to interview
him like a sharp product manager and build up a spec, then hand off a document.

You will receive the running DRAFT (JSON) plus the recent conversation and his latest
message. Do THREE things and return them as JSON matching the schema:

1. Fold his latest message into the DRAFT. CARRY FORWARD everything already known — never
   blank a field you cannot improve. Fill title, one_liner, problem, trigger, actors,
   steps (the user-point-of-view flow), data_touched, edge_cases, open_questions.
2. Decide "status":
   - "finalize" ONLY when he explicitly signals he is done (e.g. "that's it", "done",
     "write it up", "generate the doc", "ship it", "pronto", "pode gerar") OR the draft
     is clearly complete AND he confirms. When in doubt, prefer one more question.
   - "cancel" if he abandons it ("forget it", "nevermind", "cancel", "deixa pra lá").
   - "clarifying" otherwise.
3. When status is "clarifying", write "reply": a SHORT WhatsApp message that briefly
   acknowledges what you captured and asks the FEWEST, highest-value questions to close
   the biggest gaps (usually 1-3, as a short batch — never interrogate). When status is
   "finalize" or "cancel", "reply" may be null.

Rules:
- Write "reply" in ${langName(lang)}. Keep it conversational and tight; no markdown
  headers, no numbered spec dumps — this is a chat message, not the document.
- Focus the spec on the FLOW FROM THE USER'S POINT OF VIEW (what the user does and sees),
  not implementation internals, unless he brings them up.
- Do not invent facts he hasn't given; put genuine unknowns in open_questions and ask
  about the important ones.`;
}

export function buildClarifyUser(owner, { draftJson, transcript, latest, nowStr }) {
  return `Current date/time: ${nowStr}

Running DRAFT (JSON, may be mostly empty on the first turn):
${draftJson}

Recent conversation:
${transcript || "(none)"}

${owner}'s latest message: ${latest}`;
}

// ---- Document generation (ALWAYS English) ------------------------------------
// Returns PROSE (markdown), not JSON — skill.js reads the text blocks directly.
export function buildDocSystem() {
  return `You are a product writer. Turn the feature DRAFT (JSON) into a clean Markdown
feature-spec document, written from the POINT OF VIEW OF THE USER.

Output ONLY the Markdown document — no preamble, no code fences around the whole thing.
Write in ENGLISH regardless of the draft's language (translate any non-English content;
keep proper nouns). Use exactly this skeleton, omitting a section only if it would be
empty:

# <Feature title>

## Summary
<one-sentence summary>

## Problem / motivation
<the pain this solves and why it matters>

## User flow (from the user's point of view)
1. <how the user triggers / starts it>
2. <next step the user takes or sees>
...

## Actors
- <who is involved>

## Data & services touched
<systems, data, integrations involved>

## Edge cases & open questions
- <edge case>
- **Open:** <unresolved question>

---
*Drafted by @secretary on WhatsApp. Save to the repo and refine.*

Keep it concise and concrete. Do not add sections that aren't in the skeleton.`;
}

export function buildDocUser({ draftJson }) {
  return `Feature DRAFT (JSON):
${draftJson}`;
}

// ---- slug for the filename ---------------------------------------------------
// Lowercase, strip accents, non-alphanumeric -> "-", collapse/trim. Fallback "feature".
export function slugify(title) {
  const s = String(title || "")
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "") // strip diacritics
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
  return s || "feature";
}

// ============================================================================
//  USER-FACING SCAFFOLDING STRINGS (localized).
//  Fixed messages only — the conversational turn reply is generated in-language by
//  the model (buildClarifySystem). Keep BOTH en + pt; any other language is produced
//  from the `en` copy by the orchestrator's send() translation fallback.
// ============================================================================
const REPLY = {
  en: {
    thinkingError: () => "I hit an error while thinking. Try again?",
    firstFallback: () =>
      "Got it — let's spec this out. What problem does this feature solve, and how does a user start it?",
    continueFallback: () => "Got it. Anything else to capture, or should I write it up?",
    cancelled: () => "Okay, dropped that feature request.",
    renderError: () =>
      "I couldn't generate the document. Your notes are safe — say \"write it up\" to try again.",
    sendFailed: () =>
      "I wrote the spec but couldn't send the file. Error in the log — try again?",
    docCaption: ({ title }) =>
      `Here's the spec for "${title}". Save it and drop it into your repo. 📄`,
  },
  pt: {
    thinkingError: () => "Tive um erro ao processar. Pode tentar de novo?",
    firstFallback: () =>
      "Beleza — vamos detalhar. Que problema essa funcionalidade resolve, e como o usuário começa o fluxo?",
    continueFallback: () =>
      "Anotado. Falta capturar mais alguma coisa, ou já posso escrever o documento?",
    cancelled: () => "Ok, descartei esse pedido de funcionalidade.",
    renderError: () =>
      'Não consegui gerar o documento. Suas anotações estão salvas — diga "pode escrever" para tentar de novo.',
    sendFailed: () =>
      "Escrevi a spec mas não consegui enviar o arquivo. O erro está no log — tentar de novo?",
    docCaption: ({ title }) =>
      `Aqui está a spec de "${title}". Salve e coloque no seu repositório. 📄`,
  },
};

// Pick the reply set for a language, falling back to English (which the
// orchestrator's send() then translates for any non-en/pt language).
export function reply(lang) {
  return REPLY[lang] || REPLY.en;
}
